Repository NVIDIA-NeMo/Curator, pull requests merged in 2024-10, with the labels that each got.

#256 Fix 255 - Improve separate_by_metadata performance for jsonl files
  nemo_curator/scripts/separate_by_metadata.py
  nemo_curator/utils/file_utils.py
  tests/test_separate_by_metadata.py
Labels: enhancement

#276 Pin to spacy<3.8 temporarily to unblock CI
  requirements/requirements.txt
  requirements/requirements_cuda12x.txt
  requirements/requirements_rapids_nightly.txt
Labels: meta

#273 Pin Rapids to 24.8 for 0.5.0 Release
  requirements/requirements.txt
  requirements/requirements_cuda12x.txt
  requirements/requirements_rapids_nightly.txt
Labels: meta

#261 Add Curator and Spark example in docs
  docs/user-guide/index.rst
  docs/user-guide/sparkother.rst
Labels: documentation

#253 Add GPU CI/CD
  .github/workflows/_build_container.yml
  .github/workflows/gpuci.yml
  Dockerfile
  README.md
  nemo_curator/utils/import_utils.py
Labels: gpuci

#294 Update Crossfit to 0.0.6 and cudf nightly to 24.12
  requirements/requirements.txt
  requirements/requirements_rapids_nightly.txt
Labels: gpuci

#269 Add fineweb classifer documentation
  docs/user-guide/api/classifiers.rst
  docs/user-guide/distributeddataclassification.rst
  docs/user-guide/index.rst
Labels: documentation

#258 Update deduplication docs
  docs/user-guide/cpuvsgpu.rst
  docs/user-guide/gpudeduplication.rst
Labels: documentation

#317 Write to file without including "filename" column
  nemo_curator/datasets/doc_dataset.py
  nemo_curator/utils/distributed_utils.py
  tests/test_io.py
Labels: gpuci

#238 Add image documentation
  README.md
  docs/user-guide/api/datasets.rst
  docs/user-guide/api/image/classifiers.rst
  docs/user-guide/api/image/embedders.rst
  docs/user-guide/api/image/index.rst
  docs/user-guide/api/index.rst
  docs/user-guide/assets/diagram.png
  docs/user-guide/assets/sorted_sequence_dataloader.png
  docs/user-guide/assets/zeroshot_ablations.png
  docs/user-guide/distributeddataclassification.rst
  docs/user-guide/image/classifiers/aesthetic.rst
  docs/user-guide/image/classifiers/index.rst
  docs/user-guide/image/classifiers/nsfw.rst
  docs/user-guide/image/datasets.rst
  docs/user-guide/image/embedders.rst
  docs/user-guide/image/gettingstarted.rst
  docs/user-guide/image/index.rst
  docs/user-guide/index.rst
  nemo_curator/datasets/image_text_pair_dataset.py
  nemo_curator/image/classifiers/aesthetic.py
  nemo_curator/image/classifiers/base.py
  nemo_curator/image/classifiers/nsfw.py
  nemo_curator/image/embedders/base.py
  nemo_curator/image/embedders/timm.py
  setup.py
Labels: documentation

#319 [REVIEW] Add pre-commit hook for DCO and pre-commit check
  .pre-commit-config.yaml
Labels: meta

#302 [REVIEW] Speedup Connected Components
  nemo_curator/modules/fuzzy_dedup.py
  nemo_curator/scripts/fuzzy_deduplication/connected_components.py
Labels: enhancement, gpuci

#330 Fix Jaccard Shuffle Error when Result is Empty + Overwrite using fuzzy_dedup cache
  docs/user-guide/gpudeduplication.rst
  examples/fuzzy_deduplication.py
  nemo_curator/modules/fuzzy_dedup.py
  nemo_curator/utils/fuzzy_dedup_utils/shuffle_utils.py
  tests/test_fuzzy_dedup.py
Labels: gpuci, bugfix
