Repository NVIDIA-NeMo/Curator, pull requests merged in 2024-12, with the labels that each got.

#407 Add pin to NeMo Toolkit
  requirements/requirements.txt
  setup.py
Labels: meta, gpuci

#363 Multilingual Domain Classifier
  README.md
  docs/user-guide/api/classifiers.rst
  docs/user-guide/cpuvsgpu.rst
  docs/user-guide/distributeddataclassification.rst
  examples/classifiers/README.md
  examples/classifiers/multilingual_domain_example.py
  nemo_curator/classifiers/__init__.py
  nemo_curator/classifiers/domain.py
  nemo_curator/scripts/classifiers/README.md
  nemo_curator/scripts/classifiers/multilingual_domain_classifier_inference.py
  pyproject.toml
Labels: gpuci

#423 Dockerfile should use the correct nvidia channel to install libcu*
  Dockerfile
Labels: bug, gpuci

#433 Pin RAPIDS versions for r0.6.0
  pyproject.toml
Labels: gpuci

#285 Add blocksize to `DocumentDataset.read_*` that uses `dask_cudf.read_*`
  docs/user-guide/bestpractices.rst
  nemo_curator/_compat.py
  nemo_curator/datasets/doc_dataset.py
  nemo_curator/utils/distributed_utils.py
  tests/test_io.py
  tests/test_read_data.py
  tests/test_separate_by_metadata.py
Labels: gpuci

#448 ci: Bump `_build_container` workflow
  .github/workflows/gpuci.yml
Labels: gpuci

#442 Update fuzzy dedup test args to account for minhash algo changes.
  tests/test_fuzzy_dedup.py
Labels: gpuci, bugfix

#421 Add `tests/test_classifiers.py` PyTests
  nemo_curator/classifiers/aegis.py
  pyproject.toml
  tests/test_classifiers.py
Labels: gpuci

#449 Change filename column name to file_name
  nemo_curator/datasets/doc_dataset.py
  nemo_curator/datasets/parallel_dataset.py
  nemo_curator/download/arxiv.py
  nemo_curator/download/commoncrawl.py
  nemo_curator/download/doc_builder.py
  nemo_curator/download/wikipedia.py
  nemo_curator/modules/dataset_ops.py
  nemo_curator/utils/distributed_utils.py
  nemo_curator/utils/file_utils.py
  tests/test_io.py
  tests/test_read_data.py
  tests/test_separate_by_metadata.py
  tests/test_shuffle.py
  tutorials/peft-curation-with-sdg/docbuilder.py
  tutorials/peft-curation-with-sdg/synthetic_gen.py
  tutorials/peft-curation/docbuilder.py
  tutorials/tinystories/docbuilder.py
Labels: gpuci
