Repository NVIDIA-NeMo/Curator, pull requests merged in 2024-11, with the labels that each got.

#340 V0.5.0 forward merge
  nemo_curator/image/classifiers/nsfw.py
  setup.py
  tutorials/image-curation/helper.py
  tutorials/image-curation/image-curation.ipynb
  tutorials/synthetic-retrieval-evaluation/SDG-Retriever_Eval_Tutorial.ipynb
  tutorials/tinystories/main.py
Labels: meta, gpuci

#347 Update `id_column` and `id_column_type` names in PyTest
  tests/test_semdedup.py
Labels: gpuci

#323 Add `nemo_curator.__version__`, `--version`, and `-v` displays
  README.md
  docs/user-guide/gpudeduplication.rst
  nemo_curator/__init__.py
  nemo_curator/pii/algorithm.py
  nemo_curator/scripts/add_id.py
  nemo_curator/scripts/blend_datasets.py
  nemo_curator/scripts/classifiers/aegis_classifier_inference.py
  nemo_curator/scripts/classifiers/domain_classifier_inference.py
  nemo_curator/scripts/classifiers/fineweb_edu_classifier_inference.py
  nemo_curator/scripts/classifiers/quality_classifier_inference.py
  nemo_curator/scripts/download_and_extract.py
  nemo_curator/scripts/filter_documents.py
  nemo_curator/scripts/find_exact_duplicates.py
  nemo_curator/scripts/find_matching_ngrams.py
  nemo_curator/scripts/find_pii_and_deidentify.py
  nemo_curator/scripts/fuzzy_deduplication/buckets_to_edges.py
  nemo_curator/scripts/fuzzy_deduplication/compute_minhashes.py
  nemo_curator/scripts/fuzzy_deduplication/connected_components.py
  nemo_curator/scripts/fuzzy_deduplication/jaccard_compute.py
  nemo_curator/scripts/fuzzy_deduplication/jaccard_shuffle.py
  nemo_curator/scripts/fuzzy_deduplication/map_buckets.py
  nemo_curator/scripts/fuzzy_deduplication/minhash_lsh.py
  nemo_curator/scripts/get_common_crawl_urls.py
  nemo_curator/scripts/get_wikipedia_urls.py
  nemo_curator/scripts/make_data_shards.py
  nemo_curator/scripts/prepare_fasttext_training_data.py
  nemo_curator/scripts/prepare_task_data.py
  nemo_curator/scripts/remove_matching_ngrams.py
  nemo_curator/scripts/semdedup/clustering.py
  nemo_curator/scripts/semdedup/compute_embeddings.py
  nemo_curator/scripts/semdedup/extract_dedup_data.py
  nemo_curator/scripts/separate_by_metadata.py
  nemo_curator/scripts/text_cleaning.py
  nemo_curator/scripts/train_fasttext.py
  nemo_curator/scripts/verify_classification_results.py
  nemo_curator/utils/script_utils.py
  pyproject.toml
  requirements/requirements.txt
  requirements/requirements_cuda12x.txt
  requirements/requirements_image.txt
  requirements/requirements_rapids_nightly.txt
  setup.py
Labels: gpuci

#352 build: Improve caching
  .github/workflows/_build_container.yml
  .github/workflows/gpuci.yml
  Dockerfile
Labels: gpuci

#354 ci: Run on main
  .github/workflows/gpuci.yml
  Dockerfile
Labels: gpuci

#355 ci: Run on merge commit
  .github/workflows/gpuci.yml
  Dockerfile
Labels: gpuci

#357 build: Add conda env to `$PATH`
  .github/workflows/gpuci.yml
  Dockerfile
Labels: gpuci

#351 Fix `gpu_exact_dups` due to deprecated flag
  nemo_curator/scripts/find_exact_duplicates.py
Labels: bugfix

#358 Ko3n1g/sarahyurick/ci/build test publish wheel
  .github/workflows/build-test-publish-wheel.yml
  Dockerfile
  nemo_curator/__init__.py
Labels: gpuci

#356 Add `build-test-publish-wheel` CI file
  .github/workflows/build-test-publish-wheel.yml
  Dockerfile
  nemo_curator/__init__.py
  nemo_curator/package_info.py
  pyproject.toml
Labels: gpuci

#372 Fix broken NeMo dependencies
  .github/workflows/test.yml
  Dockerfile
  README.md
  docs/user-guide/image/gettingstarted.rst
  nemo_curator/filters/code.py
  pyproject.toml
  tutorials/image-curation/image-curation.ipynb
  tutorials/synthetic-data-hello-world/Synthetic Data Generation - Hello World Examples.ipynb
Labels: gpuci

#313 MinHash improvement using minhash_permuted
  nemo_curator/_compat.py
  nemo_curator/modules/fuzzy_dedup.py
Labels: enhancement, gpuci

#316 Retiring `text_bytes_aware_shuffle` to use `shuffle` directly
  nemo_curator/modules/fuzzy_dedup.py
  nemo_curator/utils/fuzzy_dedup_utils/io_utils.py
  nemo_curator/utils/fuzzy_dedup_utils/shuffle_utils.py
Labels: gpuci

#173 Add Multiple Model Classification example
  tutorials/distributed_data_classification/pytorch-ensemble-classification.ipynb
Labels: documentation

#326 Add codepath for computing buckets without int conversion
  docs/user-guide/gpudeduplication.rst
  examples/fuzzy_deduplication.py
  nemo_curator/modules/fuzzy_dedup.py
  nemo_curator/scripts/fuzzy_deduplication/minhash_lsh.py
  nemo_curator/utils/fuzzy_dedup_utils/io_utils.py
  tests/test_fuzzy_dedup.py
Labels: enhancement, gpuci
