Repository NVIDIA-NeMo/Curator, pull requests merged in 2025-07, with the labels that each got.

#769 Implement safe extraction methods for tar files to prevent path traversal
  nemo_curator/download/arxiv.py
  tests/test_classifiers.py
Labels: r0.9.0

#799 cp: `Add tests for safe extraction methods in test_download.py (794)` into `r0.9.0`
  tests/test_download.py
Labels: Run CICD, cherry-pick

#798 cp: `Remove skip markers from classifier tests to enable execution on GPU (774)` into `r0.9.0`
  tests/test_classifiers.py
Labels: Run CICD, cherry-pick

#800 cp: `Uncomment pip install comment in Image Tutorial (791)` into `r0.9.0`
  tutorials/image-curation/image-curation.ipynb
Labels: Run CICD, cherry-pick

#811 cp: `Nit fixes in Single GPU Tutorial (802)` into `r0.9.0`
  tutorials/single_node_tutorial/single_gpu_tutorial.ipynb
Labels: Run CICD, cherry-pick

#807 Set upperbound on datasets version
  pyproject.toml
Labels: r0.9.0

#813 Multimodal dapt curation edits
  tutorials/multimodal_dapt_curation/README.md
  tutorials/multimodal_dapt_curation/curator/README.md
  tutorials/multimodal_dapt_curation/curator/requirements.txt
  tutorials/multimodal_dapt_curation/ingest/README.md
Labels: r0.9.0

#816 cp: `Multimodal dapt curation edits (813)` into `r0.9.0`
  tutorials/multimodal_dapt_curation/README.md
  tutorials/multimodal_dapt_curation/curator/README.md
  tutorials/multimodal_dapt_curation/curator/requirements.txt
  tutorials/multimodal_dapt_curation/ingest/README.md
Labels: Run CICD, cherry-pick

#810 Fix Nemotron-CC tutorial
  tutorials/nemotron-cc/nemotron_cc.ipynb
Labels: r0.9.0

#819 cp: `Fix Nemotron-CC tutorial (810)` into `r0.9.0`
  tutorials/nemotron-cc/nemotron_cc.ipynb
Labels: Run CICD, cherry-pick

#820 [Tutorials] Update the model specs in the SDG Hello World notebook
  tutorials/synthetic-data-hello-world/README.md
  tutorials/synthetic-data-hello-world/Synthetic Data Generation - Hello World Examples.ipynb
Labels: r0.9.0

#823 cp: `[Tutorials] Update the model specs in the SDG Hello World notebook (820)` into `r0.9.0`
  tutorials/synthetic-data-hello-world/README.md
  tutorials/synthetic-data-hello-world/Synthetic Data Generation - Hello World Examples.ipynb
Labels: Run CICD, cherry-pick

#829 Final fixes for Nemotron-CC tutorial
  tutorials/nemotron-cc/nemotron_cc.ipynb
Labels: r0.9.0

#841 chore: Add new trustees and vetters to the copy-pr-bot configuration
  .github/copy-pr-bot.yaml
Labels: ray-api

#842 cp: `chore: Add new trustees and vetters to the copy-pr-bot configuration (841)` into `ray-api`
  .github/copy-pr-bot.yaml
Labels: Run CICD, cherry-pick

#849 cp: `ci: Add community-bot (846)` into `ray-api`
  .github/workflows/close-inactive-issue-pr.yml
  .github/workflows/community-bot.yml
Labels: Run CICD, cherry-pick

#860 docs: changelog update
  CHANGELOG.md
Labels: r0.9.0, community-request

#862 cp: `docs: changelog update (860)` into `r0.9.0`
  CHANGELOG.md
Labels: Run CICD, cherry-pick
