Repository NVIDIA-NeMo/Curator, pull requests merged in 2025-01, with the labels that each got.

#464 Pin CrossFit 0.0.8
  pyproject.toml
Labels: gpuci

#466 chore: update changelog 0.6.0
  .github/workflows/release.yml
  CHANGELOG.md
Labels: r0.6.0

#467 fix: Generate version number string
  nemo_curator/package_info.py
Labels: r0.6.0

#458 Fix image curation on latest RAPIDS
  nemo_curator/datasets/image_text_pair_dataset.py
  nemo_curator/image/classifiers/base.py
  nemo_curator/image/embedders/base.py
  nemo_curator/utils/cudf_utils.py
Labels: gpuci

#457 Clean up internal column logic in `_run_classifier_helper` function
  nemo_curator/classifiers/base.py
  tests/test_classifiers.py
Labels: gpuci

#465 Make `add_filename` str/bool
  docs/user-guide/documentdataset.rst
  nemo_curator/datasets/doc_dataset.py
  nemo_curator/datasets/parallel_dataset.py
  nemo_curator/download/arxiv.py
  nemo_curator/download/commoncrawl.py
  nemo_curator/download/doc_builder.py
  nemo_curator/download/wikipedia.py
  nemo_curator/modules/dataset_ops.py
  nemo_curator/utils/distributed_utils.py
  nemo_curator/utils/file_utils.py
  tests/test_io.py
  tests/test_read_data.py
Labels: gpuci

#478 [REVIEW] Fix Sem Dedup
  nemo_curator/modules/semantic_dedup.py
  tests/test_semdedup.py
Labels: gpuci

#409 Create separate files for each deduplication class
  docs/user-guide/api/deduplication.rst
  nemo_curator/modules/__init__.py
  nemo_curator/modules/fuzzy_dedup.py
  nemo_curator/modules/fuzzy_dedup/_mapbuckets.py
  nemo_curator/modules/fuzzy_dedup/_shuffle.py
  nemo_curator/modules/fuzzy_dedup/bucketstoedges.py
  nemo_curator/modules/fuzzy_dedup/connectedcomponents.py
  nemo_curator/modules/fuzzy_dedup/fuzzyduplicates.py
  nemo_curator/modules/fuzzy_dedup/jaccardsimilarity.py
  nemo_curator/modules/fuzzy_dedup/lsh.py
  nemo_curator/modules/fuzzy_dedup/minhash.py
  nemo_curator/modules/semantic_dedup.py
  nemo_curator/modules/semantic_dedup/clusteringmodel.py
  nemo_curator/modules/semantic_dedup/embeddings.py
  nemo_curator/modules/semantic_dedup/semanticclusterleveldedup.py
  nemo_curator/modules/semantic_dedup/semdedup.py
  nemo_curator/scripts/fuzzy_deduplication/connected_components.py
  nemo_curator/scripts/fuzzy_deduplication/jaccard_compute.py
  nemo_curator/scripts/fuzzy_deduplication/jaccard_shuffle.py
  nemo_curator/scripts/fuzzy_deduplication/map_buckets.py
  nemo_curator/scripts/semdedup/clustering.py
  nemo_curator/scripts/semdedup/compute_embeddings.py
  nemo_curator/scripts/semdedup/extract_dedup_data.py
  tutorials/dapt-curation/README.md
  tutorials/pretraining-data-curation/red-pajama-v2-curation-tutorial.ipynb
  tutorials/single_node_tutorial/single_gpu_tutorial.ipynb
  tutorials/zyda2-tutorial/1_fuzzy_dedup/2_buckets_to_edges.py
  tutorials/zyda2-tutorial/1_fuzzy_dedup/3_connected_components.py
Labels: gpuci

#495 Update to support Python 3.12
  .github/workflows/test.yml
  Dockerfile
  README.md
  docs/user-guide/image/gettingstarted.rst
  pyproject.toml
Labels: meta, gpuci

#415 Create notebook tutorials for distributed data classifiers
  README.md
  nemo_curator/sample_dataframe.py
  tutorials/README.md
  tutorials/distributed_data_classification/README.md
  tutorials/distributed_data_classification/aegis-classification.ipynb
  tutorials/distributed_data_classification/content-type-classification.ipynb
  tutorials/distributed_data_classification/domain-classification.ipynb
  tutorials/distributed_data_classification/fineweb-edu-classification.ipynb
  tutorials/distributed_data_classification/instruction-data-guard-classification.ipynb
  tutorials/distributed_data_classification/multilingual-domain-classification.ipynb
  tutorials/distributed_data_classification/prompt-task-complexity-classification.ipynb
  tutorials/distributed_data_classification/pytorch-ensemble-classification.ipynb
  tutorials/distributed_data_classification/quality-classification.ipynb
Labels: documentation

#498 Update fuzzy deduplication to skip false positive checks as the default
  examples/fuzzy_deduplication.py
  nemo_curator/modules/config.py
  nemo_curator/modules/fuzzy_dedup/minhash.py
  nemo_curator/scripts/fuzzy_deduplication/README.md
  nemo_curator/scripts/fuzzy_deduplication/compute_minhashes.py
  tests/test_fuzzy_dedup.py
Labels: enhancement, gpuci

#503 Fix DAPT tutorial
  config/sem_dedup_config.yaml
  docs/user-guide/semdedup.rst
  nemo_curator/modules/config.py
  nemo_curator/modules/semantic_dedup/embeddings.py
  nemo_curator/modules/semantic_dedup/semdedup.py
  nemo_curator/scripts/semdedup/compute_embeddings.py
  tutorials/dapt-curation/README.md
  tutorials/dapt-curation/code/configs/text_semantic_dedupe_config.yaml
  tutorials/dapt-curation/code/main.py
  tutorials/dapt-curation/code/utils.py
Labels: gpuci
