Repository NVIDIA-NeMo/Curator, pull requests merged in 2025-03, with the labels that each got.

#581 Add batched pairwise similarity method for Semantic Dedup
  config/sem_dedup_config.yaml
  docs/user-guide/semdedup.rst
  nemo_curator/modules/config.py
  nemo_curator/modules/semantic_dedup/semanticclusterleveldedup.py
  nemo_curator/modules/semantic_dedup/semdedup.py
  nemo_curator/scripts/semdedup/extract_dedup_data.py
  nemo_curator/utils/semdedup_utils.py
  tests/test_semdedup.py
  tutorials/dapt-curation/code/configs/text_semantic_dedupe_config.yaml
  tutorials/image-curation/image-curation.ipynb
  tutorials/peft-curation-with-sdg/config/sem_dedup_config.yaml
Labels: gpuci

#477 Support `dask_expr` migration into `dask.dataframe`
  nemo_curator/_compat.py
  nemo_curator/utils/fuzzy_dedup_utils/shuffle_utils.py
Labels: gpuci

#583 ci(feat): Codecov
  .coveragerc
  .github/workflows/gpuci.yml
  .github/workflows/test.yml
  Dockerfile
  codecov.yml
Labels: gpuci

#586 docs: Update changelog for `0.7.0`
  CHANGELOG.md
Labels: r0.7.0, Run CICD

#587 Cherry pick `docs: Update changelog for `0.7.0` (586)` into `r0.7.0`
  CHANGELOG.md
Labels: Run CICD, cherry-pick

#591 Fix Transformers + Cuda Context bug in NeMo Curator
  nemo_curator/classifiers/aegis.py
  pyproject.toml
Labels: gpuci, bugfix, r0.7.0

#592 Cherry pick `Fix Transformers + Cuda Context bug in NeMo Curator (591)` into `r0.7.0`
  nemo_curator/classifiers/aegis.py
  pyproject.toml
Labels: Run CICD, cherry-pick

#596 `output_file_path` nit in classifier tutorials
  tutorials/distributed_data_classification/aegis-classification.ipynb
  tutorials/distributed_data_classification/content-type-classification.ipynb
  tutorials/distributed_data_classification/domain-classification.ipynb
  tutorials/distributed_data_classification/fineweb-edu-classification.ipynb
  tutorials/distributed_data_classification/fineweb-edu-ensemble-classification.ipynb
  tutorials/distributed_data_classification/fineweb-mixtral-edu-classification.ipynb
  tutorials/distributed_data_classification/fineweb-nemotron-edu-classification.ipynb
  tutorials/distributed_data_classification/instruction-data-guard-classification.ipynb
  tutorials/distributed_data_classification/multilingual-domain-classification.ipynb
  tutorials/distributed_data_classification/prompt-task-complexity-classification.ipynb
  tutorials/distributed_data_classification/pytorch-ensemble-classification.ipynb
  tutorials/distributed_data_classification/quality-classification.ipynb
Labels: documentation

#600 Fix rate limit in SDG Retriever Eval Tutorial
  tutorials/synthetic-retrieval-evaluation/DeDup.py
Labels: r0.7.0

#601 Cherry pick `Fix rate limit in SDG Retriever Eval Tutorial (600)` into `r0.7.0`
  tutorials/synthetic-retrieval-evaluation/DeDup.py
Labels: Run CICD, cherry-pick

#604 Add metrics tests
  tests/test_metrics.py
Labels: gpuci

#605 Add SDG tests
  .github/workflows/test.yml
  nemo_curator/synthetic/async_nemotron.py
  nemo_curator/synthetic/nemotron.py
  tests/synthetic/test_async_nemotron.py
  tests/synthetic/test_async_nemotron_cc.py
  tests/synthetic/test_generator.py
  tests/synthetic/test_mixtral.py
  tests/synthetic/test_nemotron.py
  tests/synthetic/test_nemotron_cc.py
  tests/synthetic/test_no_format.py
Labels: gpuci

#603 Add image unit tests
  nemo_curator/datasets/image_text_pair_dataset.py
  tests/image/classifiers/test_aesthetic.py
  tests/image/classifiers/test_nsfw.py
  tests/image/embedders/test_timm.py
  tests/image/test_image_text_pair_dataset.py
  tests/image_data/00000.idx
  tests/image_data/00000.tar
Labels: gpuci

#602 Automatically run gpuCI on PR updates
  .github/workflows/gpuci.yml
Labels: gpuci

#606 Add miscellaneous unit tests
  .github/workflows/gpuci.yml
  nemo_curator/services/nemo_client.py
  nemo_curator/utils/distributed_utils.py
  nemo_curator/utils/file_utils.py
  nemo_curator/utils/import_utils.py
  tests/services/__init__.py
  tests/services/test_model_client.py
  tests/services/test_nemo_client.py
  tests/services/test_openai_client.py
  tests/test_classifiers.py
  tests/test_slurm.py
  tests/utils/test_bitext_distributed_utils.py
  tests/utils/test_config_utils.py
  tests/utils/test_distributed_utils.py
  tests/utils/test_download_utils.py
  tests/utils/test_file_utils.py
Labels: gpuci

#613 Add changelog for 0.7.1
  CHANGELOG.md
Labels: r0.7.0

#614 Cherry pick `Add changelog for 0.7.1 (613)` into `r0.7.0`
  CHANGELOG.md
Labels: Run CICD, cherry-pick
