Repository NVIDIA-NeMo/Curator, pull requests merged in 2025-08, with the labels that each got.

#831 [Tutorials] Lazy import GPU modules in the Llama Nemotron tutorial
  tutorials/llama-nemotron-data-curation/README.md
  tutorials/llama-nemotron-data-curation/main.py
Labels: ray-api

#871 cp: `update LLM PII redaction file - fix issue 828 (868)` into `ray-api`
  tutorials/curator-llm-pii/PII-LLM-modification-Enron.ipynb
  tutorials/curator-llm-pii/PII-LLM-modification-tutorial.ipynb
  tutorials/curator-llm-pii/README.md
Labels: Run CICD, cherry-pick

#885 docs: Updating version switcher
  docs/conf.py
  docs/versions1.json
Labels: documentation, ray-api

#882 cp: `docs: api link fixes (865)` into `ray-api`
  docs/reference/index.md
Labels: Run CICD, cherry-pick

#892 Fix exception when blocksize is set
  nemo_curator/utils/distributed_utils.py
Labels: gpuci, ray-api, community-request

#915 Add Connected components
  nemo_curator/modules/fuzzy_dedup/connectedcomponents.py
  ray-curator/ray_curator/backends/experimental/ray_actor_pool/raft_adapter.py
  ray-curator/ray_curator/stages/deduplication/fuzzy/connected_components.py
  ray-curator/ray_curator/utils/file_utils.py
  ray-curator/tests/stages/deduplication/fuzzy/test_connected_components_stage.py
Labels: gpuci

#939 Llane/readme image fix
  README.md
  docs/_images/ablation.png
  docs/_images/scaling.png
  docs/_images/text-benchmarks.png
Labels: ray-api

#834 Adding get client feature
  ray-curator/ray_curator/core/__init__.py
  ray-curator/ray_curator/core/client.py
  ray-curator/ray_curator/core/constants.py
  ray-curator/ray_curator/core/utils.py
  ray-curator/ray_curator/examples/quickstart.py
  ray-curator/ray_curator/metrics/__init__.py
  ray-curator/ray_curator/metrics/constants.py
  ray-curator/ray_curator/metrics/utils.py
  ray-curator/tests/backends/utils.py
  ray-curator/tests/core/__init__.py
  ray-curator/tests/core/test_get_ray_client.py
Labels: gpuci

#913 Update community-bot to add issues to shard project
  .github/workflows/community-bot.yml
Labels: ray-api
