Repository NVIDIA-NeMo/Curator, pull requests merged in 2025-05, with the labels that each got.

#697 Update classifier and semantic deduplication PyTests
  tests/test_classifiers.py
  tests/test_semdedup.py
Labels: gpuci

#701 Add 0.8.0 changelog
  CHANGELOG.md
Labels: r0.8.0

#702 Cherry pick `Add 0.8.0 changelog (701)` into `r0.8.0`
  CHANGELOG.md
Labels: Run CICD, cherry-pick

#698 Simplifying clustering logic
  nemo_curator/modules/semantic_dedup/clusteringmodel.py
Labels: gpuci

#691 ci: Add codecov rules
  .github/workflows/test.yml
  CONTRIBUTING.md
  codecov.yml
  nemo_curator/hello.py
  tests/test_hello.py
Labels: gpuci
