Repository NVIDIA-NeMo/Curator, pull requests merged in 2025-02, with the labels that each got.

#479 Enable ADD ID to work with CPU/GPU both
  nemo_curator/modules/add_id.py
  nemo_curator/scripts/add_id.py
  tests/test_add_id.py
Labels: gpuci

#491 Add Pooling Strategy Option for embedding creation
  nemo_curator/modules/config.py
  nemo_curator/modules/semantic_dedup/embeddings.py
  nemo_curator/modules/semantic_dedup/semdedup.py
  tests/test_semdedup.py
Labels: gpuci

#519 Add Partition On Logic
  nemo_curator/datasets/doc_dataset.py
  nemo_curator/utils/distributed_utils.py
  tests/test_io.py
Labels: gpuci

#497 Update model nomenclature
  docs/user-guide/cpuvsgpu.rst
  docs/user-guide/distributeddataclassification.rst
  examples/classifiers/README.md
  examples/classifiers/instruction_data_guard_example.py
  nemo_curator/classifiers/aegis.py
  nemo_curator/classifiers/content_type.py
  nemo_curator/classifiers/domain.py
  nemo_curator/classifiers/prompt_task_complexity.py
  nemo_curator/classifiers/quality.py
  nemo_curator/scripts/classifiers/README.md
  nemo_curator/scripts/classifiers/instruction_data_guard_classifier_inference.py
  tests/test_classifiers.py
  tutorials/distributed_data_classification/README.md
  tutorials/distributed_data_classification/content-type-classification.ipynb
  tutorials/distributed_data_classification/domain-classification.ipynb
  tutorials/distributed_data_classification/instruction-data-guard-classification.ipynb
  tutorials/distributed_data_classification/multilingual-domain-classification.ipynb
  tutorials/distributed_data_classification/prompt-task-complexity-classification.ipynb
  tutorials/distributed_data_classification/quality-classification.ipynb
Labels: documentation

#525 Ensure AddId Module has any backend
  nemo_curator/modules/add_id.py
Labels: gpuci

#509 Removal logic for fuzzy / exact (no class abstraction)
  docs/user-guide/gpudeduplication.rst
  examples/exact_deduplication.py
  examples/fuzzy_deduplication.py
  nemo_curator/modules/config.py
  nemo_curator/modules/exact_dedup.py
  nemo_curator/modules/fuzzy_dedup/fuzzyduplicates.py
  nemo_curator/utils/duplicates_removal.py
  tests/test_duplicates_removal.py
  tests/test_exact_dedup.py
  tests/test_fuzzy_dedup.py
Labels: gpuci

#540 Fix GPU CI tests by creating 1 cluster across sessions
  conftest.py
  tests/test_backends.py
  tests/test_classifiers.py
  tests/test_fuzzy_dedup.py
  tests/test_semdedup.py
Labels: gpuci

#527 Add Nemotron CC SDG Pipelines and Pre-processing/Post-Processing Stages
  docs/user-guide/api/filters.rst
  docs/user-guide/api/misc.rst
  docs/user-guide/api/modifiers.rst
  docs/user-guide/api/synthetic.rst
  docs/user-guide/syntheticdata.rst
  nemo_curator/filters/__init__.py
  nemo_curator/filters/heuristic_filter.py
  nemo_curator/modifiers/__init__.py
  nemo_curator/modifiers/line_remover.py
  nemo_curator/modifiers/markdown_remover.py
  nemo_curator/modifiers/quotation_remover.py
  nemo_curator/modifiers/slicer.py
  nemo_curator/modules/__init__.py
  nemo_curator/modules/joiner.py
  nemo_curator/modules/splitter.py
  nemo_curator/synthetic/__init__.py
  nemo_curator/synthetic/async_nemotron_cc.py
  nemo_curator/synthetic/nemotron_cc.py
  nemo_curator/synthetic/prompts.py
  tests/test_cleaning.py
  tests/test_filters.py
  tests/test_joiner.py
  tests/test_nemotron_cc.py
  tests/test_splitter.py
  tests/test_splitter_joiner.py
Labels: gpuci

#483 Minor CrossFit improvements
  nemo_curator/classifiers/base.py
  nemo_curator/classifiers/prompt_task_complexity.py
Labels: gpuci

#555 Bump RAPIDS stable to 25.02 and RAPIDS nightly to 25.04
  pyproject.toml
  tests/test_read_data.py
Labels: gpuci

#543 Enable PyTests for Nemotron-CC classifiers
  nemo_curator/scripts/classifiers/fineweb_mixtral_edu_classifier_inference.py
  nemo_curator/scripts/classifiers/fineweb_nemotron_edu_classifier_inference.py
  pyproject.toml
  tests/test_classifiers.py
Labels: gpuci

#522 Fix bugs in retriever sdg notebook
  nemo_curator/filters/synthetic.py
  tutorials/nemo-retriever-synthetic-data-generation/README.md
  tutorials/nemo-retriever-synthetic-data-generation/config/config-fiqa.yaml
  tutorials/nemo-retriever-synthetic-data-generation/config/config-nq.yaml
  tutorials/nemo-retriever-synthetic-data-generation/config/config.yaml
  tutorials/nemo-retriever-synthetic-data-generation/main.py
  tutorials/nemo-retriever-synthetic-data-generation/notebooks/quickstart.ipynb
  tutorials/nemo-retriever-synthetic-data-generation/retriever_evalset_generator.py
  tutorials/nemo-retriever-synthetic-data-generation/sample_data/sample_data_rawdoc.jsonl
Labels: r0.7.0

#450 Update `get_all_files_paths_under` examples to include `keep_extensions`
  docs/user-guide/distributeddataclassification.rst
  docs/user-guide/documentdataset.rst
  docs/user-guide/qualityfiltering.rst
  docs/user-guide/sparkother.rst
  docs/user-guide/taskdecontamination.rst
  examples/classifier_filtering.py
  examples/identify_languages.py
  examples/task_decontamination.py
  nemo_curator/scripts/find_exact_duplicates.py
  nemo_curator/scripts/fuzzy_deduplication/compute_minhashes.py
  nemo_curator/scripts/prepare_fasttext_training_data.py
  nemo_curator/utils/file_utils.py
  tests/test_read_data.py
  tutorials/pretraining-data-curation/red-pajama-v2-curation-tutorial.ipynb
  tutorials/single_node_tutorial/single_gpu_tutorial.ipynb
  tutorials/tinystories/main.py
  tutorials/zyda2-tutorial/1_fuzzy_dedup/0_minhash.py
Labels: gpuci

#560 Cherry pick `Fix bugs in retriever sdg notebook (522)` into `r0.7.0`
  nemo_curator/filters/synthetic.py
  tutorials/nemo-retriever-synthetic-data-generation/README.md
  tutorials/nemo-retriever-synthetic-data-generation/config/config-fiqa.yaml
  tutorials/nemo-retriever-synthetic-data-generation/config/config-nq.yaml
  tutorials/nemo-retriever-synthetic-data-generation/config/config.yaml
  tutorials/nemo-retriever-synthetic-data-generation/main.py
  tutorials/nemo-retriever-synthetic-data-generation/notebooks/quickstart.ipynb
  tutorials/nemo-retriever-synthetic-data-generation/retriever_evalset_generator.py
  tutorials/nemo-retriever-synthetic-data-generation/sample_data/sample_data_rawdoc.jsonl
Labels: Run CICD, cherry-pick

#563 Few minor updates in single gpu tutorial
  tutorials/single_node_tutorial/single_gpu_tutorial.ipynb
Labels: r0.7.0

#570 Minor updates to duplicate removal
  examples/exact_deduplication.py
  nemo_curator/modules/config.py
  nemo_curator/modules/exact_dedup.py
  nemo_curator/modules/fuzzy_dedup/fuzzyduplicates.py
  nemo_curator/utils/duplicates_removal.py
  tests/test_duplicates_removal.py
  tests/test_exact_dedup.py
Labels: gpuci

#574 Add read_custom_data to DocumentDataset
  nemo_curator/datasets/doc_dataset.py
  nemo_curator/download/doc_builder.py
  nemo_curator/scripts/semdedup/clustering.py
  nemo_curator/scripts/semdedup/compute_embeddings.py
  nemo_curator/scripts/semdedup/extract_dedup_data.py
  nemo_curator/utils/distributed_utils.py
  tests/test_dataset.py
  tests/test_io.py
  tests/test_read_data.py
Labels: gpuci

#575 Add KMeans `random_state` to semantic deduplication configs
  config/sem_dedup_config.yaml
  docs/user-guide/semdedup.rst
  nemo_curator/modules/config.py
  nemo_curator/modules/semantic_dedup/clusteringmodel.py
  nemo_curator/modules/semantic_dedup/embeddings.py
  nemo_curator/modules/semantic_dedup/semanticclusterleveldedup.py
  nemo_curator/modules/semantic_dedup/semdedup.py
  nemo_curator/scripts/semdedup/clustering.py
  nemo_curator/scripts/semdedup/compute_embeddings.py
  nemo_curator/scripts/semdedup/extract_dedup_data.py
  tests/test_semdedup.py
  tutorials/dapt-curation/code/configs/text_semantic_dedupe_config.yaml
  tutorials/peft-curation-with-sdg/config/sem_dedup_config.yaml
Labels: gpuci
