Repository NVIDIA-NeMo/Curator, pull requests merged in 2025-04, with the labels that each got.

#598 Sem Dedup Refactor (bug fixes / tests / simplifcation)
  config/sem_dedup_config.yaml
  docs/user-guide/semdedup.rst
  nemo_curator/modules/config.py
  nemo_curator/modules/semantic_dedup/clusteringmodel.py
  nemo_curator/modules/semantic_dedup/semanticclusterleveldedup.py
  nemo_curator/modules/semantic_dedup/semdedup.py
  nemo_curator/scripts/semdedup/clustering.py
  nemo_curator/scripts/semdedup/extract_dedup_data.py
  nemo_curator/utils/script_utils.py
  nemo_curator/utils/semdedup_utils.py
  tests/test_argument_helper.py
  tests/test_semdedup.py
  tutorials/dapt-curation/code/configs/text_semantic_dedupe_config.yaml
  tutorials/dapt-curation/code/utils.py
  tutorials/image-curation/image-curation.ipynb
  tutorials/peft-curation-with-sdg/config/sem_dedup_config.yaml
  tutorials/peft-curation-with-sdg/main.py
Labels: gpuci

#618 Semantic Dedup bug fix to support string id types
  nemo_curator/utils/semdedup_utils.py
  tests/test_semdedup.py
Labels: gpuci

#617 SemDedup outputs docs_to_remove + All dedup modules extend BaseDeduplicationModule
  examples/semdedup_example.py
  nemo_curator/modules/base.py
  nemo_curator/modules/exact_dedup.py
  nemo_curator/modules/fuzzy_dedup/fuzzyduplicates.py
  nemo_curator/modules/semantic_dedup/semanticclusterleveldedup.py
  nemo_curator/modules/semantic_dedup/semdedup.py
  nemo_curator/utils/duplicates_removal.py
  nemo_curator/utils/semdedup_utils.py
  tests/test_duplicates_removal.py
  tests/test_fuzzy_dedup.py
  tests/test_semdedup.py
  tutorials/dapt-curation/code/main.py
  tutorials/dapt-curation/code/utils.py
  tutorials/image-curation/image-curation.ipynb
  tutorials/peft-curation-with-sdg/main.py
  tutorials/peft-curation-with-sdg/synthetic_gen.py
  tutorials/tinystories/main.py
Labels: gpuci

#620 Fix gpuci errors around huggingface timeouts
  tests/test_classifiers.py
Labels: meta, gpuci

#580 Hard Negative Mining
  nemo_curator/modules/semantic_dedup/clusteringmodel.py
  tests/test_semdedup.py
  tutorials/nemo-retriever-synthetic-data-generation/config/config.py
  tutorials/nemo-retriever-synthetic-data-generation/config/hard-negative-mining-config.yaml
  tutorials/nemo-retriever-synthetic-data-generation/main.py
  tutorials/nemo-retriever-synthetic-data-generation/mine_hard_negatives.py
  tutorials/nemo-retriever-synthetic-data-generation/repartition.py
  tutorials/nemo-retriever-synthetic-data-generation/retriever_evalset_generator.py
  tutorials/nemo-retriever-synthetic-data-generation/retriever_hardnegative_miner.py
  tutorials/nemo-retriever-synthetic-data-generation/sample_data/hard-neg-mining/hard-neg-input-data.jsonl
  tutorials/nemo-retriever-synthetic-data-generation/sample_data/sdg/sample_data_rawdoc.jsonl
Labels: gpuci

#625 [FIX] Fix Kmeans Cancelled Error
  nemo_curator/modules/semantic_dedup/clusteringmodel.py
Labels: gpuci

#637 Cherry pick `Fix bug when removing extensions from a filename (631)` into `r0.8.0`
  nemo_curator/utils/distributed_utils.py
  tests/utils/test_distributed_utils.py
Labels: gpuci, Run CICD, cherry-pick

#639 Pin Rapids versions to 25.02 for r0.8.0
  pyproject.toml
Labels: gpuci, r0.8.0

#641 Cherry pick `Pin Rapids versions to 25.02 for r0.8.0 (639)` into `r0.8.0`
  pyproject.toml
Labels: gpuci, Run CICD, cherry-pick

#653 Ruff formatting for `nemo_curator/tasks` and `nemo_curator/modules`
  nemo_curator/modules/__init__.py
  nemo_curator/modules/add_id.py
  nemo_curator/modules/base.py
  nemo_curator/modules/config.py
  nemo_curator/modules/dataset_ops.py
  nemo_curator/modules/exact_dedup.py
  nemo_curator/modules/filter.py
  nemo_curator/modules/fuzzy_dedup/__init__.py.py
  nemo_curator/modules/fuzzy_dedup/_mapbuckets.py
  nemo_curator/modules/fuzzy_dedup/_shuffle.py
  nemo_curator/modules/fuzzy_dedup/bucketstoedges.py
  nemo_curator/modules/fuzzy_dedup/connectedcomponents.py
  nemo_curator/modules/fuzzy_dedup/fuzzyduplicates.py
  nemo_curator/modules/fuzzy_dedup/jaccardsimilarity.py
  nemo_curator/modules/fuzzy_dedup/lsh.py
  nemo_curator/modules/fuzzy_dedup/minhash.py
  nemo_curator/modules/joiner.py
  nemo_curator/modules/meta.py
  nemo_curator/modules/modify.py
  nemo_curator/modules/semantic_dedup/__init__.py
  nemo_curator/modules/semantic_dedup/clusteringmodel.py
  nemo_curator/modules/semantic_dedup/embeddings.py
  nemo_curator/modules/semantic_dedup/semanticclusterleveldedup.py
  nemo_curator/modules/semantic_dedup/semdedup.py
  nemo_curator/modules/splitter.py
  nemo_curator/modules/task.py
  nemo_curator/modules/to_backend.py
  nemo_curator/tasks/__init__.py
  nemo_curator/tasks/downstream_task.py
  nemo_curator/tasks/metrics.py
Labels: gpuci

#657 Ruff formatting for `nemo_curator/classifiers` and `nemo_curator/filters`
  nemo_curator/classifiers/__init__.py
  nemo_curator/classifiers/aegis.py
  nemo_curator/classifiers/base.py
  nemo_curator/classifiers/content_type.py
  nemo_curator/classifiers/domain.py
  nemo_curator/classifiers/fineweb_edu.py
  nemo_curator/classifiers/prompt_task_complexity.py
  nemo_curator/classifiers/quality.py
  nemo_curator/filters/__init__.py
  nemo_curator/filters/bitext_filter.py
  nemo_curator/filters/classifier_filter.py
  nemo_curator/filters/code.py
  nemo_curator/filters/doc_filter.py
  nemo_curator/filters/heuristic_filter.py
  nemo_curator/filters/models/qe_models.py
  nemo_curator/filters/synthetic.py
Labels: gpuci

#659 Ruff : `nemo_curator/services` and `nemo_curator/modifier` and `log.py` and `_compat.py`
  .github/workflows/ruff.yml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  README.md
  nemo_curator/_compat.py
  nemo_curator/log.py
  nemo_curator/modifiers/__init__.py
  nemo_curator/modifiers/async_llm_pii_modifier.py
  nemo_curator/modifiers/c4.py
  nemo_curator/modifiers/doc_modifier.py
  nemo_curator/modifiers/fasttext.py
  nemo_curator/modifiers/line_remover.py
  nemo_curator/modifiers/llm_pii_modifier.py
  nemo_curator/modifiers/markdown_remover.py
  nemo_curator/modifiers/newline_normalizer.py
  nemo_curator/modifiers/pii_modifier.py
  nemo_curator/modifiers/quotation_remover.py
  nemo_curator/modifiers/slicer.py
  nemo_curator/modifiers/unicode_reformatter.py
  nemo_curator/modifiers/url_remover.py
  nemo_curator/services/__init__.py
  nemo_curator/services/conversation_formatter.py
  nemo_curator/services/model_client.py
  nemo_curator/services/nemo_client.py
  nemo_curator/services/openai_client.py
  pyproject.toml
Labels: gpuci

#664 Ruff formatting for `nemo_curator/datasets`, `nemo_curator/image`, `nemo_curator/nemo_run`, and `nemo_curator/pii`
  nemo_curator/datasets/__init__.py
  nemo_curator/datasets/doc_dataset.py
  nemo_curator/datasets/image_text_pair_dataset.py
  nemo_curator/datasets/parallel_dataset.py
  nemo_curator/image/classifiers/aesthetic.py
  nemo_curator/image/classifiers/base.py
  nemo_curator/image/classifiers/nsfw.py
  nemo_curator/image/embedders/base.py
  nemo_curator/image/embedders/timm.py
  nemo_curator/nemo_run/slurm.py
  nemo_curator/pii/algorithm.py
  nemo_curator/pii/constants.py
  nemo_curator/pii/custom_batch_analyzer_engine.py
  nemo_curator/pii/custom_nlp_engine.py
  nemo_curator/pii/recognizers/address_recognizer.py
Labels: gpuci

#662 Ruff formatting for `nemo_curator/synthetic` and `nemo_curator/download`
  nemo_curator/download/__init__.py
  nemo_curator/download/arxiv.py
  nemo_curator/download/commoncrawl.py
  nemo_curator/download/doc_builder.py
  nemo_curator/download/wikipedia.py
  nemo_curator/download/zh_stopwords.py
  nemo_curator/synthetic/__init__.py
  nemo_curator/synthetic/async_nemotron.py
  nemo_curator/synthetic/async_nemotron_cc.py
  nemo_curator/synthetic/error.py
  nemo_curator/synthetic/generator.py
  nemo_curator/synthetic/mixtral.py
  nemo_curator/synthetic/nemotron.py
  nemo_curator/synthetic/nemotron_cc.py
  nemo_curator/synthetic/no_format.py
  nemo_curator/synthetic/prompts.py
Labels: gpuci

#667 Ruff formatting for `tests/image` and `tests/synthetic`
  tests/image/classifiers/test_aesthetic.py
  tests/image/classifiers/test_nsfw.py
  tests/image/embedders/test_timm.py
  tests/image/test_image_text_pair_dataset.py
  tests/synthetic/test_async_nemotron.py
  tests/synthetic/test_async_nemotron_cc.py
  tests/synthetic/test_generator.py
  tests/synthetic/test_mixtral.py
  tests/synthetic/test_nemotron.py
  tests/synthetic/test_nemotron_cc.py
  tests/synthetic/test_no_format.py
Labels: gpuci

#655 Ruff : `nemo_curator/utils`
  nemo_curator/utils/config_utils.py
  nemo_curator/utils/constants.py
  nemo_curator/utils/decorators.py
  nemo_curator/utils/distributed_utils.py
  nemo_curator/utils/download_utils.py
  nemo_curator/utils/duplicates_removal.py
  nemo_curator/utils/file_utils.py
  nemo_curator/utils/fuzzy_dedup_utils/id_mapping.py
  nemo_curator/utils/fuzzy_dedup_utils/io_utils.py
  nemo_curator/utils/fuzzy_dedup_utils/merge_utils.py
  nemo_curator/utils/fuzzy_dedup_utils/output_map_utils.py
  nemo_curator/utils/fuzzy_dedup_utils/shuffle_utils.py
  nemo_curator/utils/gpu_utils.py
  nemo_curator/utils/image/transforms.py
  nemo_curator/utils/import_utils.py
  nemo_curator/utils/llm_pii_utils.py
  nemo_curator/utils/module_utils.py
  nemo_curator/utils/script_utils.py
  nemo_curator/utils/semdedup_utils.py
  nemo_curator/utils/text_utils.py
  tests/utils/test_distributed_utils.py
Labels: gpuci

#668 Ruff formatting for remaining tests
  tests/test_classifiers.py
  tests/test_dataset.py
  tests/test_download.py
  tests/test_duplicates_removal.py
  tests/test_exact_dedup.py
  tests/test_filters.py
  tests/test_io.py
  tests/test_joiner.py
  tests/test_llm_pii.py
  tests/test_metrics.py
  tests/test_read_simple_bitext.py
  tests/test_sdg_pipeline_filters.py
  tests/test_slurm.py
Labels: gpuci

#663 Ruff : Update tests/services and tests/utils and another 15 test files
  conftest.py
  tests/services/test_model_client.py
  tests/services/test_nemo_client.py
  tests/services/test_openai_client.py
  tests/test_add_id.py
  tests/test_argument_helper.py
  tests/test_backends.py
  tests/test_blend_datasets.py
  tests/test_cleaning.py
  tests/test_config.py
  tests/test_fuzzy_dedup.py
  tests/test_pii_accuracy.py
  tests/test_read_data.py
  tests/test_semdedup.py
  tests/test_separate_by_metadata.py
  tests/test_shuffle.py
  tests/test_splitter.py
  tests/test_splitter_joiner.py
  tests/test_task_decontamination.py
  tests/utils/test_bitext_distributed_utils.py
  tests/utils/test_config_utils.py
  tests/utils/test_distributed_utils.py
  tests/utils/test_download_utils.py
  tests/utils/test_file_utils.py
Labels: gpuci

#670 Fix broken Aegis Permissive test
  nemo_curator/scripts/README.md
  nemo_curator/scripts/verify_classification_results.py
  pyproject.toml
  tests/test_classifiers.py
Labels: gpuci

#676 Revert PiiDeidentifier Import
  nemo_curator/modifiers/pii_modifier.py
Labels: gpuci

#672 Add asyncio to PyTest markers
  pyproject.toml
Labels: gpuci

#679 Remove conditions for Minhash
  nemo_curator/_compat.py
  nemo_curator/modules/fuzzy_dedup/minhash.py
  tests/test_read_data.py
Labels: gpuci

#678 Update RAPIDS version to 25.04
  pyproject.toml
Labels: gpuci

#685 Pin CrossFit version 0.0.9
  pyproject.toml
Labels: gpuci

#682 fixed github issue 677
  tutorials/nemo-retriever-synthetic-data-generation/README.md
  tutorials/nemo-retriever-synthetic-data-generation/mine_hard_negatives.py
  tutorials/nemo-retriever-synthetic-data-generation/retriever_hardnegative_miner.py
Labels: gpuci, r0.8.0

#687 Cherry pick Retriever hard negative mining fix (682) into r0.8.0
  tutorials/nemo-retriever-synthetic-data-generation/README.md
  tutorials/nemo-retriever-synthetic-data-generation/mine_hard_negatives.py
  tutorials/nemo-retriever-synthetic-data-generation/retriever_hardnegative_miner.py
Labels: gpuci, Run CICD, cherry-pick
