Repository NVIDIA-NeMo/Curator, pull requests merged in 2025-09, with the labels that each got.

#1006 ci: Add back gpu coverage report
  .github/actions/test-template/action.yml
  .github/workflows/cicd-main.yml
Labels: r1.0.0

#1014 cp: `Merge `examples/` directory into `tutorials/` (1010)` into `r1.0.0`
  examples/audio/__init__.py
  examples/audio/fleurs/__init__.py
  tutorials/README.md
  tutorials/audio/README.md
  tutorials/audio/fleurs/README.md
  tutorials/audio/fleurs/pipeline.py
  tutorials/audio/fleurs/pipeline.yaml
  tutorials/audio/fleurs/run.py
  tutorials/image/README.md
  tutorials/image/getting-started/README.md
  tutorials/image/getting-started/helper.py
  tutorials/image/getting-started/image_curation_example.py
  tutorials/image/getting-started/image_dedup_example.py
  tutorials/quickstart.py
  tutorials/text/README.md
  tutorials/text/distributed-data-classification/README.md
  tutorials/text/distributed-data-classification/aegis-classification.ipynb
  tutorials/text/distributed-data-classification/content-type-classification.ipynb
  tutorials/text/distributed-data-classification/domain-classification.ipynb
  tutorials/text/distributed-data-classification/fineweb-edu-classification.ipynb
  tutorials/text/distributed-data-classification/fineweb-mixtral-edu-classification.ipynb
  tutorials/text/distributed-data-classification/fineweb-nemotron-edu-classification.ipynb
  tutorials/text/distributed-data-classification/instruction-data-guard-classification.ipynb
  tutorials/text/distributed-data-classification/multilingual-domain-classification.ipynb
  tutorials/text/distributed-data-classification/prompt-task-complexity-classification.ipynb
  tutorials/text/distributed-data-classification/quality-classification.ipynb
  tutorials/text/download-and-extract/README.md
  tutorials/text/download-and-extract/download_extract_tutorial.ipynb
  tutorials/text/peft-curation/README.md
  tutorials/text/peft-curation/main.py
  tutorials/text/peft-curation/stages.py
  tutorials/text/tinystories/README.md
  tutorials/text/tinystories/main.py
  tutorials/text/tinystories/stages.py
  tutorials/video/README.md
  tutorials/video/getting-started/README.md
  tutorials/video/getting-started/video_read_example.py
  tutorials/video/getting-started/video_split_clip_example.py
Labels: Run CICD, cherry-pick

#1017 cp: `ci: Add build id to dockerfile (1016)` into `r1.0.0`
  docker/Dockerfile
Labels: Run CICD, cherry-pick

#1018 Make Ray Datas log less verbose
  nemo_curator/backends/experimental/ray_data/executor.py
Labels: r1.0.0

#1019 cp: `Add TextSemanticDeduplicationWorkflow (1000)` into `r1.0.0`
  nemo_curator/stages/deduplication/semantic/pairwise.py
  nemo_curator/stages/deduplication/semantic/workflow.py
  nemo_curator/stages/text/deduplication/semantic.py
  tests/stages/text/deduplication/test_semantic.py
Labels: Run CICD, cherry-pick

#1020 cp: `Make Ray Datas log less verbose (1018)` into `r1.0.0`
  nemo_curator/backends/experimental/ray_data/executor.py
Labels: Run CICD, cherry-pick

#1023 Adding tutorial for image curation pipeline
  tutorials/image/getting-started/README.md
  tutorials/image/getting-started/helper.py
  tutorials/image/getting-started/image_curation_example.py
  tutorials/image/getting-started/image_dedup_example.py
Labels: r1.0.0

#1026 cp: `[REVIEW] Add minor overwrite mode bug fix and tests (1025)` into `r1.0.0`
  nemo_curator/utils/file_utils.py
  tests/stages/text/io/writer/test_jsonl.py
  tests/stages/text/io/writer/test_parquet.py
Labels: Run CICD, cherry-pick

#1033 cp: `Small updates for PEFT and Tinystories tutorials (1021)` into `r1.0.0`
  tutorials/text/peft-curation/README.md
  tutorials/text/peft-curation/main.py
  tutorials/text/tinystories/README.md
  tutorials/text/tinystories/main.py
Labels: Run CICD, cherry-pick

#1035 cp: `✨ Set up comprehensive Copilot instructions with complete API design architecture and framework overview for Python 3.12 and CUDA 12 (1031)` into `r1.0.0`
  .github/copilot-instructions.md
Labels: Run CICD, cherry-pick

#1041 cp: `Check codebase for typos and fix identified issues (1036)` into `r1.0.0`
  docs/reference/index.md
  nemo_curator/backends/experimental/ray_data/executor.py
  nemo_curator/backends/xenna/executor.py
Labels: Run CICD, cherry-pick

#1051 cp: `Fix image curation tutorial batch sizes for typical GPUs (1050)` into `r1.0.0`
  tutorials/image/getting-started/README.md
Labels: Run CICD, cherry-pick

#1004 ci: Re-organize curator dep
  .github/workflows/cicd-main.yml
  docker/Dockerfile
  pyproject.toml
  uv.lock
Labels: r1.0.0

#1055 ci: Use pytest-cov
  pyproject.toml
  uv.lock
Labels: r1.0.0

#1060 update contribution guide
  CONTRIBUTING.md
Labels: r1.0.0

#1059 Allow RayActorPool (RAFT) to run after Xenna
  nemo_curator/backends/experimental/ray_actor_pool/executor.py
  tests/backends/experimental/ray_actor_pool/__init__.py
  tests/backends/experimental/ray_actor_pool/test_executor.py
  tests/stages/deduplication/semantic/test_kmeans.py
Labels: r1.0.0

#1062 cp: `Allow RayActorPool (RAFT) to run after Xenna (1059)` into `r1.0.0`
  nemo_curator/backends/experimental/ray_actor_pool/executor.py
  tests/backends/experimental/ray_actor_pool/__init__.py
  tests/backends/experimental/ray_actor_pool/test_executor.py
  tests/stages/deduplication/semantic/test_kmeans.py
Labels: Run CICD, cherry-pick

#1071 ci: Remove texinfo from ffmpeg install
  .github/workflows/cicd-main.yml
  docker/common/install_ffmpeg.sh
Labels: r1.0.0

#1072 ci: Skip kaldiio installation
  pyproject.toml
  uv.lock
Labels: r1.0.0

#1078 cp: `ci: Skip kaldiio installation (1072)` into `r1.0.0`
  pyproject.toml
  uv.lock
Labels: Run CICD, cherry-pick

#1068 Allow jsonl/parquet to rewrite the same file
  nemo_curator/stages/text/io/writer/base.py
  tests/stages/text/io/writer/test_jsonl.py
  tests/stages/text/io/writer/test_parquet.py
Labels: r1.0.0

#1097 typo fix in tutorial script
  tutorials/audio/fleurs/pipeline.py
Labels: r1.0.0, tutorials

#1083 Feedback updates to text tutorials
  tutorials/text/deduplication/semantic/semantic_e2e.ipynb
  tutorials/text/deduplication/semantic/semantic_step_by_step.ipynb
  tutorials/text/distributed-data-classification/aegis-classification.ipynb
  tutorials/text/distributed-data-classification/content-type-classification.ipynb
  tutorials/text/distributed-data-classification/domain-classification.ipynb
  tutorials/text/distributed-data-classification/fineweb-edu-classification.ipynb
  tutorials/text/distributed-data-classification/fineweb-mixtral-edu-classification.ipynb
  tutorials/text/distributed-data-classification/fineweb-nemotron-edu-classification.ipynb
  tutorials/text/distributed-data-classification/instruction-data-guard-classification.ipynb
  tutorials/text/distributed-data-classification/multilingual-domain-classification.ipynb
  tutorials/text/distributed-data-classification/prompt-task-complexity-classification.ipynb
  tutorials/text/distributed-data-classification/quality-classification.ipynb
  tutorials/text/download-and-extract/download_extract_tutorial.ipynb
  tutorials/text/peft-curation/README.md
  tutorials/text/peft-curation/main.py
  tutorials/text/tinystories/README.md
  tutorials/text/tinystories/main.py
Labels: r1.0.0

#1096 Video Pipeline/README Improvement
  tutorials/video/getting-started/README.md
  tutorials/video/getting-started/video_read_example.py
  tutorials/video/getting-started/video_split_clip_example.py
Labels: r1.0.0

#1107 cp: `ci: Prune unused cache entries (1091)` into `r1.0.0`
  docker/Dockerfile
Labels: Run CICD, cherry-pick

#1114 cp: `Addressing VDR comments (1094)` into `r1.0.0`
  tutorials/image/getting-started/README.md
  tutorials/image/getting-started/image_curation_example.py
  tutorials/image/getting-started/image_dedup_example.py
Labels: Run CICD, cherry-pick

#1115 cp: `Skip IV2 Unit Test if package not installed (1111)` into `r1.0.0`
  tests/models/test_internvideo2.py
  tests/models/test_internvideo2_mm.py
Labels: Run CICD, cherry-pick

#1116 cp: `Llane/docs audio modality staging (1028)` into `r1.0.0`
  CONTRIBUTING.md
  docs/about/concepts/audio/asr-pipeline.md
  docs/about/concepts/audio/audio-batch.md
  docs/about/concepts/audio/curation-pipeline.md
  docs/about/concepts/audio/index.md
  docs/about/concepts/audio/manifests-ingest.md
  docs/about/concepts/audio/quality-metrics.md
  docs/about/concepts/audio/text-integration.md
  docs/about/concepts/image/index.md
  docs/about/concepts/index.md
  docs/about/concepts/text/index.md
  docs/about/concepts/video/index.md
  docs/about/key-features.md
  docs/admin/config/deployment-environments.md
  docs/admin/config/index.md
  docs/admin/installation.md
  docs/curate-audio/index.md
  docs/curate-audio/load-data/custom-manifests.md
  docs/curate-audio/load-data/fleurs-dataset.md
  docs/curate-audio/load-data/index.md
  docs/curate-audio/load-data/local-files.md
  docs/curate-audio/process-data/asr-inference/index.md
  docs/curate-audio/process-data/asr-inference/nemo-models.md
  docs/curate-audio/process-data/audio-analysis/duration-calculation.md
  docs/curate-audio/process-data/audio-analysis/format-validation.md
  docs/curate-audio/process-data/audio-analysis/index.md
  docs/curate-audio/process-data/index.md
  docs/curate-audio/process-data/quality-assessment/duration-filtering.md
  docs/curate-audio/process-data/quality-assessment/index.md
  docs/curate-audio/process-data/quality-assessment/wer-filtering.md
  docs/curate-audio/process-data/text-integration/index.md
  docs/curate-audio/save-export.md
  docs/curate-audio/tutorials/beginner.md
  docs/curate-audio/tutorials/index.md
  docs/curate-text/process-data/specialized-processing/task-decontamination.md
  docs/get-started/audio.md
  docs/index.md
  docs/reference/index.md
  docs/reference/infrastructure/distributed-computing.md
  docs/reference/infrastructure/index.md
  docs/reference/infrastructure/resumable-processing.md
Labels: Run CICD, cherry-pick

#1117 ci: Test latest uv and no build group first install
  docker/Dockerfile
Labels: r1.0.0

#1112 Add iv2 install guide and guard import
  .github/workflows/cicd-main.yml
  .gitignore
  external/intern_video2_installation.sh
  tutorials/video/getting-started/video_split_clip_example.py
Labels: r1.0.0

#1121 cp: `Audio curation improvements (1113)` into `r1.0.0`
  nemo_curator/stages/audio/inference/asr_nemo.py
  tests/stages/audio/inference/test_asr_nemo.py
  tutorials/audio/fleurs/README.md
  tutorials/audio/fleurs/pipeline.py
Labels: Run CICD, cherry-pick

#1125 cp: `Add iv2 install guide and guard import (1112)` into `r1.0.0`
  .github/workflows/cicd-main.yml
  .gitignore
  external/intern_video2_installation.sh
  tutorials/video/getting-started/video_split_clip_example.py
Labels: Run CICD, cherry-pick

#1101 Enhance RayClient shutdown process by resetting RAY_ADDRESS
  nemo_curator/core/client.py
  nemo_curator/core/utils.py
  nemo_curator/metrics/start_prometheus_grafana.py
Labels: r1.0.0

#1124 Video Doc Improvement
  docs/about/concepts/video/abstractions.md
  docs/curate-video/process-data/frame-extraction.md
  docs/curate-video/save-export.md
  docs/get-started/video.md
Labels: r1.0.0

#1130 cp: `Video Doc Improvement (1124)` into `r1.0.0`
  docs/about/concepts/video/abstractions.md
  docs/curate-video/process-data/frame-extraction.md
  docs/curate-video/save-export.md
  docs/get-started/video.md
Labels: Run CICD, cherry-pick

#1122 about section updates
  docs/_extensions/json_output/config.py
  docs/_extensions/json_output/content/structured.py
  docs/_extensions/json_output/core/document_discovery.py
  docs/_extensions/json_output/core/hierarchy_builder.py
  docs/_extensions/json_output/core/json_formatter.py
  docs/_extensions/json_output/processing/processor.py
  docs/_extensions/myst_codeblock_substitutions.py
  docs/about/concepts/index.md
  docs/about/index.md
  docs/about/key-features.md
  docs/about/release-notes/index.md
  docs/conf.py
Labels: documentation, r1.0.0

#1138 cp: `about section updates (1122)` into `r1.0.0`
  docs/_extensions/json_output/config.py
  docs/_extensions/json_output/content/structured.py
  docs/_extensions/json_output/core/document_discovery.py
  docs/_extensions/json_output/core/hierarchy_builder.py
  docs/_extensions/json_output/core/json_formatter.py
  docs/_extensions/json_output/processing/processor.py
  docs/_extensions/myst_codeblock_substitutions.py
  docs/about/concepts/index.md
  docs/about/index.md
  docs/about/key-features.md
  docs/about/release-notes/index.md
  docs/conf.py
Labels: Run CICD, cherry-pick

#1142 cp: `changelog (1141)` into `r1.0.0`
  CHANGELOG.md
Labels: Run CICD, cherry-pick

#1087 Llane/docs image updates
  docs/about/concepts/image/data-export-concepts.md
  docs/about/concepts/image/data-loading-concepts.md
  docs/about/concepts/image/data-processing-concepts.md
  docs/about/concepts/image/index.md
  docs/admin/deployment/slurm/image.md
  docs/admin/installation.md
  docs/curate-images/index.md
  docs/curate-images/load-data/index.md
  docs/curate-images/load-data/tar-archives.md
  docs/curate-images/load-data/webdataset.md
  docs/curate-images/process-data/classifiers/aesthetic.md
  docs/curate-images/process-data/classifiers/index.md
  docs/curate-images/process-data/classifiers/nsfw.md
  docs/curate-images/process-data/embeddings/clip-embedder.md
  docs/curate-images/process-data/embeddings/custom.md
  docs/curate-images/process-data/embeddings/index.md
  docs/curate-images/process-data/embeddings/timm.md
  docs/curate-images/process-data/filters/aesthetic.md
  docs/curate-images/process-data/filters/index.md
  docs/curate-images/process-data/filters/nsfw.md
  docs/curate-images/process-data/index.md
  docs/curate-images/save-export.md
  docs/curate-images/tutorials/beginner.md
  docs/curate-images/tutorials/dedup-workflow.md
  docs/curate-images/tutorials/index.md
  docs/get-started/image.md
Labels: documentation, r1.0.0

#1146 Llane/docs video feedback
  docs/about/release-notes/index.md
  docs/admin/installation.md
  docs/curate-images/tutorials/dedup-workflow.md
  docs/curate-video/index.md
  docs/curate-video/load-data/index.md
  docs/curate-video/process-data/captions-preview.md
  docs/curate-video/process-data/clipping.md
  docs/curate-video/process-data/embeddings.md
  docs/curate-video/process-data/filtering.md
  docs/curate-video/process-data/frame-extraction.md
  docs/curate-video/process-data/transcoding.md
  docs/curate-video/tutorials/beginner.md
  docs/curate-video/tutorials/split-dedup.md
  docs/get-started/audio.md
  docs/get-started/image.md
  docs/get-started/text.md
  docs/get-started/video.md
Labels: r1.0.0
